"""
Agent Vault service — loads the private essence bundle and provides search.

Data is generated by ~/.agent-memory/scripts/build_vault.py. The deployed
artifact is agent_vault/vault.enc: an encrypted bundle whose key is derived from
the access token (PBKDF2 + Fernet). Plaintext JSON is a local-only fallback.
No raw logs are stored; only curated summaries, project essence and analytics.
"""
import os
import re
import json
import math
import base64
import hashlib
import logging

_VAULT_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'agent_vault')

_bundle_cache = {}   # token -> {"data":..., "index":..., "embeddings":...}
_MISSING = object()

_STOP = {
    "the", "a", "an", "and", "or", "but", "to", "of", "in", "on", "for", "with",
    "is", "are", "was", "were", "be", "been", "it", "this", "that", "as", "at",
    "by", "from", "not", "no", "do", "does", "did", "so", "if", "then", "than",
    "into", "out", "up", "down", "over", "we", "i", "you", "he", "she", "they",
}


def _read_json(path):
    try:
        with open(path, 'r', encoding='utf-8') as fh:
            return json.load(fh)
    except OSError:
        return None
    except Exception as e:
        logging.warning(f"vault: failed to parse {path}: {e}")
        return None


def _decrypt_bundle(token):
    enc_path = os.path.join(_VAULT_DIR, 'vault.enc')
    blob = _read_json(enc_path)
    if not blob or not blob.get('cipher'):
        return None
    try:
        from cryptography.fernet import Fernet  # type: ignore
        salt = base64.b64decode(blob['salt'])
        key = base64.urlsafe_b64encode(hashlib.pbkdf2_hmac('sha256', token.encode(), salt, 200_000))
        payload = Fernet(key).decrypt(blob['cipher'].encode())
        return json.loads(payload.decode('utf-8'))
    except Exception as e:
        logging.info(f"vault: decryption failed (wrong token or corrupt bundle): {e}")
        return None


def _load_plaintext():
    data = _read_json(os.path.join(_VAULT_DIR, 'data.json'))
    if not data:
        return None
    return {
        'data': data,
        'index': _read_json(os.path.join(_VAULT_DIR, 'search_index.json')),
        'embeddings': _read_json(os.path.join(_VAULT_DIR, 'embeddings.json')),
    }


def _bundle(token):
    """Return the decrypted (or local plaintext) bundle for a token, cached."""
    if token in _bundle_cache:
        cached = _bundle_cache[token]
        return None if cached is _MISSING else cached
    result = _decrypt_bundle(token) if token else None
    if not result:
        # Local dev fallback: plaintext files (never deployed to a public repo).
        result = _load_plaintext()
    _bundle_cache[token] = result or _MISSING
    return result


def load_vault(token):
    b = _bundle(token)
    return b.get('data') if b else None


def _index(token):
    b = _bundle(token)
    return b.get('index') if b else None


def _embeddings(token):
    b = _bundle(token)
    return b.get('embeddings') if b else None


def _tokenize(text):
    return [t for t in re.findall(r"[a-z0-9]+", (text or "").lower()) if len(t) > 1 and t not in _STOP]


def _bm25(query, index, top_k=12, k1=1.5, b=0.75):
    postings = index.get("postings", {})
    chunks = index.get("chunks", [])
    df = index.get("df", {})
    N = index.get("N", 0) or 1
    avgdl = index.get("avgdl", 0) or 1
    q_terms = set(_tokenize(query))
    lengths = {}
    for term in q_terms:
        for cid, _tf in postings.get(term, []):
            lengths.setdefault(cid, len(_tokenize(chunks[cid]["text"])))
    scores = {}
    for term in q_terms:
        plist = postings.get(term)
        if not plist:
            continue
        idf = math.log(1 + (N - df.get(term, 0) + 0.5) / (df.get(term, 0) + 0.5))
        for cid, tf in plist:
            dl = lengths.get(cid, avgdl)
            denom = tf + k1 * (1 - b + b * dl / avgdl)
            scores[cid] = scores.get(cid, 0) + idf * (tf * (k1 + 1)) / (denom or 1)
    ranked = sorted(scores.items(), key=lambda kv: kv[1], reverse=True)[:top_k]
    return [{"score": round(s, 4), "source": chunks[cid].get("source", ""),
             "title": chunks[cid].get("title", ""), "text": chunks[cid].get("text", "")[:600]}
            for cid, s in ranked]


def _semantic(query, token, top_k=12):
    emb = _embeddings(token)
    if not emb:
        return None
    try:
        import sys
        sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
        try:
            from ai_config import get_embedding  # type: ignore
        except ImportError:
            from api.ai_config import get_embedding  # type: ignore
        qv = get_embedding(query)
        if not qv:
            return None
        scored = []
        for c in emb.get("chunks", []):
            v = c.get("embedding")
            if not v:
                continue
            dot = sum(a * b for a, b in zip(qv, v))
            na = math.sqrt(sum(a * a for a in qv))
            nb = math.sqrt(sum(b * b for b in v))
            scored.append((dot / (na * nb) if na and nb else 0, c))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [{"score": round(s, 4), "source": c.get("source", ""), "title": c.get("title", ""),
                 "text": c.get("text", "")[:600]} for s, c in scored[:top_k]]
    except Exception as e:
        logging.warning(f"vault semantic search failed, falling back to BM25: {e}")
        return None


def vault_search(query, token, top_k=12):
    query = (query or "").strip()
    if not query:
        return []
    sem = _semantic(query, token, top_k)
    if sem is not None:
        return sem
    index = _index(token)
    if not index:
        return []
    return _bm25(query, index, top_k)
